"""holy mary migration

Revision ID: 08314651dc8d
Revises: 576e423b8837
Create Date: 2024-12-10 15:33:59.890301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08314651dc8d'
down_revision = '576e423b8837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
